name: E2E Tests

on:
  push:

env:
  NODE_VERSION: 19.0.1

jobs:
  integration-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Start containers
      run: docker-compose up -d

    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: Install Dependencies
      run: npm install

    - name: Integration testing
      run: |
        npm run ci:e2e

    - name: Stop containers
      if: always()
      run: docker-compose down

      env:
        NODE_ENV: test